config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get 'contact' => 'static_pages#contact'

  get 'help' => 'static_pages#help'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end

  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title = '')
		base_title = "Q&A Game"
		if page_title.empty?
			base_title
		else
			"#{page_title} | #{base_title}"
		end
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "Contacto", contact_path %></li>
      <li><a href="#">Log in</a></li>
    </ul>
  </nav>
<table>
  <tr>
    <td><h4 class="glyphicon glyphicon-earphone"> </h4></td>
  </tr>
  <tr>
    <td><h4 class="glyphicon glyphicon-phone"> </h4></td>
  </tr>
</table>


</footer>

app/views/layouts/_header.html.erb
<!-- Fixed navbar -->
    <header class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Q&A Game", root_path, id: "logo", class: "navbar-brand" %>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
             <ul class="nav navbar-nav navbar-right">
               <li><%= link_to "Home",   root_path, class: "active" %></li>
               <li><%= link_to "Contacto",   contact_path %></li>
               <li><%= link_to "Log in", '#' %></li>
             </ul>
       </div>
      </div>
    </header>

app/views/layouts/_shim.html.erb
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="utf-8">
  <meta name="description" content="game">
  <meta name="keywords" content="game">
  <meta name="author" content="Auralabs">  
  <title><%= full_title(yield(:title)) %> </title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<%= render	'layouts/header' %>
	<div class="container">
		<%= yield %>
		<%= render 'layouts/footer' %>
	</div>
</body>
</html>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contacto") %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="http://www.railstutorial.org/#contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Ayuda") %>

    <h1>Help</h1>
    <p>
      Get help on the Ruby on Rails Tutorial at the
      <a href="http://www.railstutorial.org/#help">Rails Tutorial help
      section</a>.
      To get help on this sample app, see the
      <a href="http://www.railstutorial.org/book"><em>Ruby on Rails
      Tutorial</em> book</a>.
    </p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Q&A Game</h1>

  <%= link_to "Sign up now!", "#", class: "btn btn-lg btn-primary" %>
</div>